// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertToFormatImg(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConvertToFormatImg'](arg1, arg2, arg3, arg4);
}

export function GetFilesAsBase64(arg1) {
  return window['go']['main']['App']['GetFilesAsBase64'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFilesDialog() {
  return window['go']['main']['App']['OpenFilesDialog']();
}
