// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertToFormatImg(arg1:Array<string>,arg2:string,arg3:number,arg4:string):Promise<string>;

export function GetFilesAsBase64(arg1:Array<string>):Promise<Array<main.FileData>>;

export function Greet(arg1:string):Promise<string>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFilesDialog():Promise<Array<string>>;
